### ISSUE TITLE
vep_or_lookup_vep failure due to different row types

### ISSUE THREAD

**Issue by mkanai** [broadinstitute/gnomad_methods#475]
Hi, I got the following error when running `vep_or_lookup_vep` with gnomAD reference. It looks like the public gnomAD site table and the current Hail's VEP output have different row types. Is there any workaround?

Code:
```
import hail as hl
from gnomad.utils.vep import vep_or_lookup_vep
from gnomad.resources.grch38.gnomad import public_release
ht = hl.read_table("gs://path/to/my/table.ht")
gnomad_ht = public_release("genomes").versions["3.1.2"].ht()
ht = vep_or_lookup_vep(ht, gnomad_ht)
```
Error log:
```
Welcome to
     __  __     <>__
    / /_/ /__  __/ /
   / __  / _ `/ / /
  /_/ /_/\_,_/_/_/   version 0.2.97-937922d7f46c
LOGGING: writing to /home/hail/hail-20220829-2015-0.2.97-937922d7f46c.log
Traceback (most recent call last):
  File "/tmp/ccdff56e83c24577aded8c147ecdd87d/annotate_vep.py", line 101, in <module>
    main(args)
  File "/tmp/ccdff56e83c24577aded8c147ecdd87d/annotate_vep.py", line 40, in main
    ht = vep_or_lookup_vep(ht, gnomad_ht)
  File "/tmp/ccdff56e83c24577aded8c147ecdd87d/pyscripts_a3_5gmef.zip/gnomad/utils/vep.py", line 230, in vep_or_lookup_vep
  File "<decorator-gen-1036>", line 2, in union
  File "/opt/conda/default/lib/python3.8/site-packages/hail/typecheck/check.py", line 577, in wrapper
    return __original_func(*args_, **kwargs_)
  File "/opt/conda/default/lib/python3.8/site-packages/hail/table.py", line 2124, in union
    raise ValueError(f"'union': table {i} has a different row type.\n"
ValueError: 'union': table 0 has a different row type.
  Expected:  struct{locus: locus<GRCh38>, alleles: array<str>, vep: struct{assembly_name: str, allele_string: str, ancestral: str, context: str, end: int32, id: str, input: str, intergenic_consequences: array<struct{allele_num: int32, consequence_terms: array<str>, impact: str, minimised: int32, variant_allele: str}>, most_severe_consequence: str, motif_feature_consequences: array<struct{allele_num: int32, consequence_terms: array<str>, high_inf_pos: str, impact: str, minimised: int32, motif_feature_id: str, motif_name: str, motif_pos: int32, motif_score_change: float64, strand: int32, variant_allele: str}>, regulatory_feature_consequences: array<struct{allele_num: int32, biotype: str, consequence_terms: array<str>, impact: str, minimised: int32, regulatory_feature_id: str, variant_allele: str}>, seq_region_name: str, start: int32, strand: int32, transcript_consequences: array<struct{allele_num: int32, amino_acids: str, appris: str, biotype: str, canonical: int32, ccds: str, cdna_start: int32, cdna_end: int32, cds_end: int32, cds_start: int32, codons: str, consequence_terms: array<str>, distance: int32, domains: array<struct{db: str, name: str}>, exon: str, gene_id: str, gene_pheno: int32, gene_symbol: str, gene_symbol_source: str, hgnc_id: str, hgvsc: str, hgvsp: str, hgvs_offset: int32, impact: str, intron: str, lof: str, lof_flags: str, lof_filter: str, lof_info: str, minimised: int32, polyphen_prediction: str, polyphen_score: float64, protein_end: int32, protein_start: int32, protein_id: str, sift_prediction: str, sift_score: float64, strand: int32, swissprot: str, transcript_id: str, trembl: str, tsl: int32, uniparc: str, variant_allele: str}>, variant_class: str}}
  Table 0: struct{locus: locus<GRCh38>, alleles: array<str>, vep: struct{assembly_name: str, allele_string: str, ancestral: str, colocated_variants: array<struct{aa_allele: str, aa_maf: float64, afr_allele: str, afr_maf: float64, allele_string: str, amr_allele: str, amr_maf: float64, clin_sig: array<str>, end: int32, eas_allele: str, eas_maf: float64, ea_allele: str, ea_maf: float64, eur_allele: str, eur_maf: float64, exac_adj_allele: str, exac_adj_maf: float64, exac_allele: str, exac_afr_allele: str, exac_afr_maf: float64, exac_amr_allele: str, exac_amr_maf: float64, exac_eas_allele: str, exac_eas_maf: float64, exac_fin_allele: str, exac_fin_maf: float64, exac_maf: float64, exac_nfe_allele: str, exac_nfe_maf: float64, exac_oth_allele: str, exac_oth_maf: float64, exac_sas_allele: str, exac_sas_maf: float64, id: str, minor_allele: str, minor_allele_freq: float64, phenotype_or_disease: int32, pubmed: array<int32>, sas_allele: str, sas_maf: float64, somatic: int32, start: int32, strand: int32}>, context: str, end: int32, id: str, input: str, intergenic_consequences: array<struct{allele_num: int32, consequence_terms: array<str>, impact: str, minimised: int32, variant_allele: str}>, most_severe_consequence: str, motif_feature_consequences: array<struct{allele_num: int32, consequence_terms: array<str>, high_inf_pos: str, impact: str, minimised: int32, motif_feature_id: str, motif_name: str, motif_pos: int32, motif_score_change: float64, strand: int32, variant_allele: str}>, regulatory_feature_consequences: array<struct{allele_num: int32, biotype: str, consequence_terms: array<str>, impact: str, minimised: int32, regulatory_feature_id: str, variant_allele: str}>, seq_region_name: str, start: int32, strand: int32, transcript_consequences: array<struct{allele_num: int32, amino_acids: str, appris: str, biotype: str, canonical: int32, ccds: str, cdna_start: int32, cdna_end: int32, cds_end: int32, cds_start: int32, codons: str, consequence_terms: array<str>, distance: int32, domains: array<struct{db: str, name: str}>, exon: str, gene_id: str, gene_pheno: int32, gene_symbol: str, gene_symbol_source: str, hgnc_id: str, hgvsc: str, hgvsp: str, hgvs_offset: int32, impact: str, intron: str, lof: str, lof_flags: str, lof_filter: str, lof_info: str, minimised: int32, polyphen_prediction: str, polyphen_score: float64, protein_end: int32, protein_start: int32, protein_id: str, sift_prediction: str, sift_score: float64, strand: int32, swissprot: str, transcript_id: str, trembl: str, tsl: int32, uniparc: str, variant_allele: str}>, variant_class: str}, vep_proc_id: struct{part_idx: int32, block_idx: int32}}
  If the tables have the same fields in different orders, or some
    common and some unique fields, then the 'unify' parameter may be
    able to coerce the tables to a common type.
```

Thanks!
Masa

**Comment by jkgoodrich** [comment]
This it likely related to the issue this PR should fix https://github.com/broadinstitute/gnomad_methods/pull/439

**Comment by mkanai** [comment]
Thanks @jkgoodrich! I think now we should drop `colocated_variants` too.

**Comment by jkgoodrich** [comment]
What version of VEP is your cluster running? gnomAD v3.1.2 is used v101 and the default when starting a cluster with `--vep GRCh38` is 95 I think. Also, rather than use the sites HT (which we exclude the colocated_variants from for release) we have run VEP 101 on the context HT which will be used by default if you don't supply a reference.

Start a cluster with:
```
hailctl dataproc start cluster_name --worker-machine-type=n1-highmem-8 --worker-boot-disk-size=200 --preemptible-worker-boot-disk-size=200 --metadata=VEP_CONFIG_PATH=/vep_data/vep-gcloud.json,VEP_CONFIG_URI=file:///vep_data/vep-gcloud.json,VEP_REPLICATE=us --init=gs://gcp-public-data--gnomad/resources/vep/v101/init-vep101.sh --pkgs="git+https://github.com/broadinstitute/gnomad_methods.git@main"
```

Then:
```
import hail as hl
from gnomad.utils.vep import vep_or_lookup_vep
hl.init(default_reference='GRCh38')

ht = hl.read_table("gs://path/to/my/table.ht")
ht = vep_or_lookup_vep(ht, vep_version="101")
```

**Comment by mkanai** [comment]
I see, thanks! Yes, I was using `--vep GRCh38`.

Is this a correct way to refer the PR branch? I tried my script with this since the PR isn't merged yet, but had no luck.
```
--pkgs="git+https://github.com/broadinstitute/gnomad_methods.git@konradjk-patch-1"
```

**Comment by jkgoodrich** [comment]
Yes that is the correct way to start the cluster for that branch, but if you try out the method I showed above you shouldn't need the new branch, it should still work. You need the new branch though if using VEP 95

**Comment by mkanai** [comment]
Thanks! Unfortunately, I got a following new error with your code and cluster configuration

```
Welcome to
     __  __     <>__
    / /_/ /__  __/ /
   / __  / _ `/ / /
  /_/ /_/\_,_/_/_/   version 0.2.98-f8833c1ae16b
LOGGING: writing to /home/hail/hail-20220830-1729-0.2.98-f8833c1ae16b.log
INFO (gnomad.utils.vep 204): Using VEPed context Table from genome build GRCh38 and VEP version 101
Traceback (most recent call last):                              (0 + 96) / 2798]
  File "/tmp/33ac4b66ef6b430dbf13669a0eccb335/annotate_vep.py", line 106, in <module>
    main(args)
  File "/tmp/33ac4b66ef6b430dbf13669a0eccb335/annotate_vep.py", line 50, in main
    ht = ht.checkpoint(
  File "<decorator-gen-1022>", line 2, in checkpoint
  File "/opt/conda/default/lib/python3.8/site-packages/hail/typecheck/check.py", line 577, in wrapper
    return __original_func(*args_, **kwargs_)
  File "/opt/conda/default/lib/python3.8/site-packages/hail/table.py", line 1291, in checkpoint
    self.write(output=output, overwrite=overwrite, stage_locally=stage_locally, _codec_spec=_codec_spec)
  File "<decorator-gen-1024>", line 2, in write
  File "/opt/conda/default/lib/python3.8/site-packages/hail/typecheck/check.py", line 577, in wrapper
    return __original_func(*args_, **kwargs_)
  File "/opt/conda/default/lib/python3.8/site-packages/hail/table.py", line 1335, in write
    Env.backend().execute(ir.TableWrite(self._tir, ir.TableNativeWriter(output, overwrite, stage_locally, _codec_spec)))
  File "/opt/conda/default/lib/python3.8/site-packages/hail/backend/py4j_backend.py", line 104, in execute
    self._handle_fatal_error_from_backend(e, ir)
  File "/opt/conda/default/lib/python3.8/site-packages/hail/backend/backend.py", line 181, in _handle_fatal_error_from_backend
    raise err
  File "/opt/conda/default/lib/python3.8/site-packages/hail/backend/py4j_backend.py", line 98, in execute
    result_tuple = self._jbackend.executeEncode(jir, stream_codec, timed)
  File "/usr/lib/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1304, in __call__
  File "/opt/conda/default/lib/python3.8/site-packages/hail/backend/py4j_backend.py", line 31, in deco
    raise fatal_error_from_java_error_triplet(deepest, full, error_id) from None
hail.utils.java.FatalError: HailException: VEP command '/vep --format vcf --json --everything --allele_number --no_stats --cache --offline --minimal --assembly GRCh38 --merged --fasta /opt/vep/.vep/Homo_sapiens.GRCh38.dna.toplevel.fa.gz --plugin LoF,loftee_path:/opt/vep/Plugins/,gerp_bigwig:/opt/vep/.vep/gerp_conservation_scores.homo_sapiens.GRCh38.bw,human_ancestor_fa:/opt/vep/.vep/human_ancestor.fa.gz,conservation_file:/opt/vep/.vep/loftee.sql --dir_plugins /opt/vep/Plugins/ -o STDOUT' failed with non-zero exit status 2
  VEP Error output:
Smartmatch is experimental at /opt/vep/Plugins/de_novo_donor.pl line 175.
Smartmatch is experimental at /opt/vep/Plugins/de_novo_donor.pl line 214.
Smartmatch is experimental at /opt/vep/Plugins/splice_site_scan.pl line 191.
Smartmatch is experimental at /opt/vep/Plugins/splice_site_scan.pl line 194.
Smartmatch is experimental at /opt/vep/Plugins/splice_site_scan.pl line 238.
Smartmatch is experimental at /opt/vep/Plugins/splice_site_scan.pl line 241.

-------------------- EXCEPTION --------------------
MSG: ERROR: Cache directory /opt/vep/.vep/homo_sapiens_merged not found

STACK Bio::EnsEMBL::VEP::CacheDir::dir /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:311
STACK Bio::EnsEMBL::VEP::CacheDir::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:227
STACK Bio::EnsEMBL::VEP::CacheDir::new /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/CacheDir.pm:111
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:115
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:132
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:203
STACK toplevel /opt/vep/src/ensembl-vep/vep:228
Date (localtime)    = Tue Aug 30 17:31:06 2022
Ensembl API version = 101
---------------------------------------------------
```

**Comment by jkgoodrich** [comment]
We identified that the init located here: gs://gcp-public-data--gnomad/resources/vep/v101/init-vep101.sh tries to copy resources that no longer exist because they were removed from `gnomad-public-requester-pays` after being moved to `gcp-public-data--gnomad`. I have fixed these links in the init and copied the fixed init to the following location gs://gnomad-public-requester-pays/resources/vep/v101/init-vep101.sh which will sync to gs://gcp-public-data--gnomad/resources/vep/v101/init-vep101.sh in the next day or so

**Comment by mkanai** [comment]
Great, thank you so much for your help!
